CREATE DATABASE 'ValueLabs'
Go

IF OBJECT_ID('dbo.Employee','U') IS NOT NULL 
DROP TABLE dbo.Employee
GO

CREATE TABLE Employee(Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,Name VARCHAR(50) NOT NULL,Designation VARCHAR(50) NOT NULL,JoiningDate DATETIME NOT NULL,Salary MONEY NOT NULL);
